---
- name: Constructed Inventory
  hosts: all
  tasks:
    - name: Add constructed inventory with two existing input inventories
      ansible.controller.inventory:
        name: "Constructed Inventory"
        description: "Creating constructed inventory by adding two inventory"
        organization: Default
        kind: constructed
        input_inventories:
          - "Dynamic-APP-AWS"
          - "Dynamic"
        controller_host: 10.74.131.100
        controller_username: admin
        controller_password: redhat
        validate_certs: false
        state: present
