---
- name: Constructed Inventory
  hosts: all
    vars:
    controller_host: controller.example.com
    validate_certs: false
    controller_username: admin
    controller_password: redhat
  tasks:
    - name: Add constructed inventory with two existing input inventories
      ansible.controller.inventory:
        name: "Constructed Inventory"
        description: "Creating constructed inventory by adding two inventory"
        organization: Default
        kind: constructed
        input_inventories:
          - "Dynamic-APP-AWS"
          - "Dynamic"
        state: present
