---
- name: Constructed Inventory
  hosts: all
  vars:
    controller_host: https://10.74.131.100
    validate_certs: false
    controller_username: admin
    controller_password: redhat
  tasks:
    - name: Add constructed inventory with two existing input inventories
      ansible.controller.inventory:
        controller_username: admin
        controller_password: redhat
        name: "Constructed Inventory"
        description: "Creating constructed inventory by adding two inventory"
        organization: Default
        kind: constructed
        input_inventories:
          - "Dynamic-APP-AWS"
          - "Dynamic"
        state: present
        validate_certs: false
