---
- name: Print a message
  hosts: all
  tasks:
    - name: Display a message
      debug:
        msg: "Hello, this is a simple Ansible playbook!"

#    - name: Install Tree package
#      yum:
#        name: tree
#        state: latest

    - name: Display a message
      debug:
        msg: "{{ namedevelopment_version }}"

#    - name: Sleep for 30 seconds
#      ansible.builtin.pause:
#        seconds: 30
