---
- name: Print a message
  hosts: all
  tasks:
    - name: Display a message
      debug:
        msg: "Hello, this is a simple Ansible playbook!"

    - name: Install httpd package
      yum:
        name: httpd
        state: latest

    - name: Display a message
      debug:
        msg: "{{ namedevelopment_version }}"
